---
title: "Study_1_vignette"
author: "Anne"
date: "12/20/2021"
output: html_document
---

# I Vignette


```{r eval = FALSE}
## Anonymize and export raw data
## 
# only include those with valid ID 
Vignette_df <- Vignette_finstrain[str_length(Vignette_finstrain$ID) > 19, ] %>% dplyr::select(-dplyr::matches("Status|IPAddress|Progress|Duration|Finished|ResponseId|Name|Email|Location|Channel|Language|ID|Click|Submit|bye|Always|PROLIFIC|Reference"))

# create location variable 
Vignette_df$locat <- (names(attr(Vignette_df$locat,"labels")[match(Vignette_df$locat,attr(Vignette_df$locat,"labels"))]))

library(haven)
write_sav(Vignette_df, "../../Full_dataset/Vignette_df_full.sav")

Vignette_df <-  Vignette_df %>% dplyr::select(-dplyr::matches("Start|EndDate|consent|TEXT|cope|chal_[1-3]|threat_[1-3]|PANA|product|lang|satis_[1-3]"))

write_sav(Vignette_df, "../data/Vignette_df.sav")
```


```{r}
## Import data and data preprocessing 
library(haven)
library(tidyverse)
Vignette_df <- read_sav("../../data/Vignette_finstrain.sav")

Vignette_df <- Vignette_df %>% dplyr::mutate(exp_cond = ifelse(group == "control", 1,
                                             ifelse(group == "intervention", 2, NA)))

# drop non-valid data 
Vignette_df <- Vignette_df %>% drop_na(mani_1)
cat("Number of participants in the raw dataset:", nrow(Vignette_df), "\n")

# Rename quit items 
Vignette_df  <- Vignette_df %>% dplyr::rename(
  quit_1 = quit1_1,
  quit_2 = quit2_1, 
  quit_3 = quit2_2
)
```



```{r}

## raw dataset 
I_vignette_df_raw <- Vignette_df %>% select(matches("occ|RecordedDate|mani|quit|year|month|found|coown|indu|locat|age|gender|edu|exp_cond"))
write.csv(I_vignette_df_raw,"../03_Data/raw_data/I_vignette_df_raw.csv", row.names = FALSE)
```

## PREPROCESSING START 


```{r}
library(labelled)
library(sjlabelled)

var_label(I_vignette_df_raw$occ) <- "Occupational status"

var_label(I_vignette_df_raw$RecordedDate) <- "Recorded date"

var_label(I_vignette_df_raw$mani_1) <- "Manipulation check financial stress - 1"
var_label(I_vignette_df_raw$mani_2) <- "Manipulation check financial stress - 2"
var_label(I_vignette_df_raw$mani_3) <- "Manipulation check financial stress - 3"

var_label(I_vignette_df_raw$quit_1) <- "Quit intention - 1"
var_label(I_vignette_df_raw$quit_2) <- "Quit intention - 2"
var_label(I_vignette_df_raw$quit_3) <- "Quit intention - 3"

var_label(I_vignette_df_raw$locat) <- "Business location"

var_label(I_vignette_df_raw$year_1) <- "Year of business foundation"
var_label(I_vignette_df_raw$month_1) <- "Month of business foundation"

var_label(I_vignette_df_raw$exp_cond) <- "Experimental or control condition"

CodeBook <-
as.data.frame(rbind(
  c(
    "RecordedDate",
    var_label(I_vignette_df_raw$RecordedDate),
    paste(get_labels(I_vignette_df_raw$RecordedDate, values = "p"), collapse = ", ")
  ),
  c("mani_1",
    var_label(I_vignette_df_raw$mani_1),
    paste(get_labels(I_vignette_df_raw$mani_1, values = "p"), collapse = ", ")
  ),
  c("mani_2",
    var_label(I_vignette_df_raw$mani_2),
    paste(get_labels(I_vignette_df_raw$mani_2, values = "p"), collapse = ", ")
  ),
  c("mani_3",
    var_label(I_vignette_df_raw$mani_3),
    paste(get_labels(I_vignette_df_raw$mani_3, values = "p"), collapse = ", ")
  ),
  c("quit_1",
    var_label(I_vignette_df_raw$quit_1),
    paste(get_labels(I_vignette_df_raw$quit_1, values = "p"), collapse = ", ")
  ),
  c("quit_2",
    var_label(I_vignette_df_raw$quit_2),
    paste(get_labels(I_vignette_df_raw$quit_2, values = "p"), collapse = ", ")
  ),
  c("quit_3",
    var_label(I_vignette_df_raw$quit_3),
    paste(get_labels(I_vignette_df_raw$quit_3, values = "p"), collapse = ", ")
  ),
  c("year_1",
    var_label(I_vignette_df_raw$year_1),
    paste(get_labels(I_vignette_df_raw$year_1, values = "p"), collapse = ", ")
  ),
  c("month_1",
    var_label(I_vignette_df_raw$month_1),
    paste(get_labels(I_vignette_df_raw$month_1, values = "p"), collapse = ", ")
  ),
  c("found",
    var_label(I_vignette_df_raw$found),
    paste(get_labels(I_vignette_df_raw$found, values = "p"), collapse = ", ")
  ),
  c("coown",
    var_label(I_vignette_df_raw$coown),
    paste(get_labels(I_vignette_df_raw$coown, values = "p"), collapse = ", ")
  ),
  c("indu",
    var_label(I_vignette_df_raw$indu),
    paste(get_labels(I_vignette_df_raw$indu, values = "p"), collapse = ", ")
  ),
  c("locat",
    var_label(I_vignette_df_raw$locat),
    paste(get_labels(I_vignette_df_raw$locat, values = "p"), collapse = ", ")
  ),
  c("age_1",
    var_label(I_vignette_df_raw$age_1),
    paste(get_labels(I_vignette_df_raw$age_1, values = "p"), collapse = ", ")
  ),
  c("gender",
    var_label(I_vignette_df_raw$gender),
    paste(get_labels(I_vignette_df_raw$gender, values = "p"), collapse = ", ")
  ),
  c("edu",
    var_label(I_vignette_df_raw$edu),
    paste(get_labels(I_vignette_df_raw$edu, values = "p"), collapse = ", ")
  ),
  c("exp_cond",
    var_label(I_vignette_df_raw$exp_cond),
    paste(get_labels(I_vignette_df_raw$exp_cond, values = "p"), collapse = ", ")
  )
)
)

names(CodeBook) <- c("Variable name", "Description", "Values")

write.csv(CodeBook,"../02_Research_materials/Codebooks/I_vignette_CodeBook.csv", row.names = FALSE)
```

```{r}
## raw dataset with attentionc hecks
I_vignette_df_raw <- Vignette_df %>% select(matches("finsit|occ|RecordedDate|mani|quit|year|month|found|coown|indu|locat|age|gender|edu|exp_cond|chal_4|threat_4|satis_4"))
```


```{r  include = TRUE}
cat("Number of participants who are not entrepreneurs:", nrow(I_vignette_df_raw) - nrow(I_vignette_df_raw[!(I_vignette_df_raw$occ == 3),]), "\n")
I_vignette_df_raw <-I_vignette_df_raw[!(I_vignette_df_raw$occ == 3),]

cat("Number of entrepreneurs in the sample:", nrow(I_vignette_df_raw))
```

```{r include = TRUE}
## Remove non-founders
cat("Number of participants who are not involved in founding:", nrow(I_vignette_df_raw) - nrow(I_vignette_df_raw[!(I_vignette_df_raw$found==2),]), "\n")
I_vignette_df_raw<-I_vignette_df_raw[!(I_vignette_df_raw$found==2),]
cat("Number of founders in the sample:", nrow(I_vignette_df_raw))

```

```{r}
library(zoo)
library(lubridate)
# Make years since business foundation 
I_vignette_df_raw$year <- as.numeric(names(attr(I_vignette_df_raw$year_1,"labels")[match(I_vignette_df_raw$year_1,attr(I_vignette_df_raw$year_1,"labels"))]))

I_vignette_df_raw$month <- (names(attr(I_vignette_df_raw$month_1,"labels")[match(I_vignette_df_raw$month_1,attr(I_vignette_df_raw$month_1,"labels"))]))


I_vignette_df_raw$t1timebuiss <- as.yearmon(paste(I_vignette_df_raw$year, I_vignette_df_raw$month), "%Y %b")

I_vignette_df_raw$t1timebuiss <- as_date(I_vignette_df_raw$t1timebuiss)

I_vignette_df_raw$RecordedDate <- as_date(I_vignette_df_raw$RecordedDate)


I_vignette_df_raw$t1timebuiss <- as.numeric(difftime(I_vignette_df_raw$RecordedDate, I_vignette_df_raw$t1timebuiss, UTC,
         units = c("days")))

```


```{r include = TRUE}
## Assign ID variable
I_vignette_df_raw$ID = seq.int(nrow(I_vignette_df_raw)) 

### Attention checks
I_vignette_df_raw_fails = I_vignette_df_raw %>% dplyr::select(chal_4,threat_4,satis_4)

## create attention fails df 
att_1 <- I_vignette_df_raw[I_vignette_df_raw$chal_4 %in% c(1, 2, 3, 5), ]
att_2 <- I_vignette_df_raw[I_vignette_df_raw$threat_4 %in% c(1,2, 3, 5), ]
att_3 <- I_vignette_df_raw[I_vignette_df_raw$satis_4 %in% c(1, 3, 4, 5, 6, 7), ]

attention_fail <- rbind(att_1, att_2, att_3) %>%
  as_tibble(.)

ID_vals <- data.frame(table(attention_fail$ID))
Rows_fails <- attention_fail$ID %in% ID_vals[ID_vals$Freq > 0,1]
Att_fails <- attention_fail[Rows_fails,]

## exclude attention fails (two or more fails)
I_vignette_df_raw <- I_vignette_df_raw[!(I_vignette_df_raw$ID %in% Att_fails$ID),]

cat("Number of T1 attention fails (at least one of three attention check items failed):", nrow(unique(Att_fails)) , "\n")
cat("Number of participants after T1 attention fails removed:", nrow(I_vignette_df_raw) , "\n")

I_vignette_df_raw <- I_vignette_df_raw[, -which(names(I_vignette_df_raw) %in% c("chal_4","threat_4", "satis_4"))]

```


```{r include = TRUE}
## NA on model variables 
## 
# make gender = 3 NA 
I_vignette_df_raw$gender[I_vignette_df_raw$gender ==3] = NA

cat("Number of participants with missing data on model variables:", nrow(I_vignette_df_raw) - nrow(I_vignette_df_raw %>% drop_na(exp_cond, quit_1, quit_2, quit_3, age_1,
                                     gender, finsit_1, finsit_2, coown, t1timebuiss)), "\n")

I_vignette_df_raw<-I_vignette_df_raw %>% drop_na(exp_cond, quit_1, quit_2, quit_3, age_1,
                                     gender, finsit_1, finsit_2, coown, t1timebuiss)

cat("Final sample size:", nrow(I_vignette_df_raw))
```

## PREPROCESSING END 

## Participant characteristics

```{r}
set.seed(42)
  library(qwraps2)
# define the markup language we are working in.
# options(qwraps2_markup = "latex") is also supported.
options(qwraps2_markup = "markdown")
```


```{r}
## preprocessed dataset 
I_vignette_df_preproc <- I_vignette_df_raw
write.csv(I_vignette_df_preproc,"../03_Data/preprocessed_data/I_vignette_df_preproc.csv", row.names = FALSE)

```


```{r include = T, echo = T}
library(janitor)
# Age overview
I_vignette_df_preproc$age <- as.numeric(names(attr(I_vignette_df_preproc$age_1,"labels")[match(I_vignette_df_preproc$age_1,attr(I_vignette_df_preproc$age_1,"labels"))]))

cat("Range age: ", range(I_vignette_df_preproc$age,  na.rm = T))

cat(paste0("Mean (SD) age: ", round(mean(I_vignette_df_preproc$age, na.rm = T), 2), " (", round(sd(I_vignette_df_preproc$age, na.rm = T), 2), ")"))

# Coownership
tabyl(I_vignette_df_preproc$coown)

# Country 
library(dplyr)
library(zoo)
library(lubridate)
tabyl(I_vignette_df_preproc$locat)

# Time since business foundation 
cat("Range of days since business foundation: " , range(I_vignette_df_preproc$t1timebuiss, na.rm = T))

cat("Mean years since business foundation: ", mean(I_vignette_df_preproc$t1timebuiss/365,  na.rm = T))

cat("SD days since business foundation: ", sd(I_vignette_df_preproc$t1timebuiss,  na.rm = T))

sd(I_vignette_df_preproc$t1timebuiss,  na.rm = T)/365

tabyl(I_vignette_df_preproc$locat)
tabyl(I_vignette_df_preproc$gender)

tabyl(I_vignette_df_preproc$exp_cond)

# Industry (8 = Arts and entertainment)
I_vignette_df_preproc$indu <- ifelse(I_vignette_df_preproc$indu_7_TEXT == "Music/Education" | I_vignette_df_preproc$indu_7_TEXT  == "Art & Media" | I_vignette_df_preproc$indu_7_TEXT  == "Entertainment" | I_vignette_df_preproc$indu_7_TEXT  == "Arts" |  I_vignette_df_preproc$indu_7_TEXT  == "Fitness influencer and online coach" | I_vignette_df_preproc$indu_7_TEXT  == "Events" | I_vignette_df_preproc$indu_7_TEXT == "Fashion" |  I_vignette_df_preproc$indu_7_TEXT  == "Hospitality events & catering"| I_vignette_df_preproc$indu_7_TEXT == "Design" | I_vignette_df_preproc$indu_7_TEXT == "Photography" | I_vignette_df_preproc$indu_7_TEXT == "photographic" | I_vignette_df_preproc$indu_7_TEXT == "Events" |  I_vignette_df_preproc$indu_7_TEXT  == "art" | I_vignette_df_preproc$indu_7_TEXT  == "arts" | I_vignette_df_preproc$indu_7_TEXT  == "Entertainment Industry" | I_vignette_df_preproc$indu_7_TEXT  == "The arts" | I_vignette_df_preproc$indu_7_TEXT  == "Children’s Entertainment" |  I_vignette_df_preproc$indu_7_TEXT  == "Art" | I_vignette_df_preproc$indu_7_TEXT  == "Entertainment Industry/ Video Production" |                                     I_vignette_df_preproc$indu_7_TEXT  == "Arts and Entertainment" | I_vignette_df_preproc$indu_7_TEXT  == "entertainment/betting" | I_vignette_df_preproc$indu_7_TEXT  == "Balloon gifts" | I_vignette_df_preproc$indu_7_TEXT  == "Entertainment and Sales" | I_vignette_df_preproc$indu_7_TEXT  == "entertainment", 8, I_vignette_df_preproc$indu)

I_vignette_df_preproc$indu <- ifelse(I_vignette_df_preproc$indu_7_TEXT == "beauty industry" | I_vignette_df_preproc$indu_7_TEXT == "beauty" | I_vignette_df_preproc$indu_7_TEXT == "Language services" | I_vignette_df_preproc$indu_7_TEXT == "Teaching" | I_vignette_df_preproc$indu_7_TEXT == "Legal" | I_vignette_df_preproc$indu_7_TEXT == "Outdoor pursuits" | I_vignette_df_preproc$indu_7_TEXT == "Education" | I_vignette_df_preproc$indu_7_TEXT  == "Tourism" |  I_vignette_df_preproc$indu_7_TEXT  == "Travel & Tourism" |
I_vignette_df_preproc$indu_7_TEXT == "wellness" | I_vignette_df_preproc$indu_7_TEXT == "Gardening" | I_vignette_df_preproc$indu_7_TEXT == "Exercise" | I_vignette_df_preproc$indu_7_TEXT == "Cleaning" | I_vignette_df_preproc$indu_7_TEXT == "Food" | I_vignette_df_preproc$indu_7_TEXT == "Charity" | I_vignette_df_preproc$indu_7_TEXT == "Horse breeding" | I_vignette_df_preproc$indu_7_TEXT == "Training" | I_vignette_df_preproc$indu_7_TEXT == "Education" | I_vignette_df_preproc$indu_7_TEXT == "Animal Care" | I_vignette_df_preproc$indu_7_TEXT == "hospitality" | I_vignette_df_preproc$indu_7_TEXT == "Hospitality" | I_vignette_df_preproc$indu_7_TEXT == "fitness" |  I_vignette_df_preproc$indu_7_TEXT == "Personal services" |  I_vignette_df_preproc$indu_7_TEXT == "personal care" | I_vignette_df_preproc$indu_7_TEXT == "personal services" | I_vignette_df_preproc$indu_7_TEXT == "Services" | I_vignette_df_preproc$indu_7_TEXT == "services" |  I_vignette_df_preproc$indu_7_TEXT == "BEAUTY" | I_vignette_df_preproc$indu_7_TEXT == "publishing" | I_vignette_df_preproc$indu_7_TEXT == "service" | I_vignette_df_preproc$indu_7_TEXT == "Training" | I_vignette_df_preproc$indu_7_TEXT == "Hairdressing" | I_vignette_df_preproc$indu_7_TEXT == "Catering Services" |  I_vignette_df_preproc$indu_7_TEXT == "tertiary sector" | I_vignette_df_preproc$indu_7_TEXT == "pet services" | I_vignette_df_preproc$indu_7_TEXT == "home services" | I_vignette_df_preproc$indu_7_TEXT == "Psychotherapy" | I_vignette_df_preproc$indu_7_TEXT == "cosmetic" , 3, I_vignette_df_preproc$indu)

I_vignette_df_preproc$indu <- ifelse(I_vignette_df_preproc$indu_7_TEXT == "marketing" | I_vignette_df_preproc$indu_7_TEXT == "Marketing" |  I_vignette_df_preproc$indu_7_TEXT == "Business services" | I_vignette_df_preproc$indu_7_TEXT == "Consultancy" | I_vignette_df_preproc$indu_7_TEXT == "Marketing and Advertising" | I_vignette_df_preproc$indu_7_TEXT == "Marketing / copywriting mainly for the tech sector" | I_vignette_df_preproc$indu_7_TEXT == "Energy Sales Services", 2, I_vignette_df_preproc$indu)

I_vignette_df_preproc$indu <- ifelse(I_vignette_df_preproc$indu_7_TEXT == "Craft" | I_vignette_df_preproc$indu_7_TEXT == "hand made, textile design" | I_vignette_df_preproc$indu_7_TEXT == "craft", 5, I_vignette_df_preproc$indu)

I_vignette_df_preproc$indu <- ifelse(I_vignette_df_preproc$indu_7_TEXT == "Engineering", 6, I_vignette_df_preproc$indu)

I_vignette_df_preproc$indu <- ifelse(I_vignette_df_preproc$indu_7_TEXT == "transportation" | I_vignette_df_preproc$indu_7_TEXT == "Selling antiques and second hand goods.", 4, I_vignette_df_preproc$indu)

I_vignette_df_preproc$indu <- ifelse(I_vignette_df_preproc$indu_7_TEXT == "3D Content Creator" | I_vignette_df_preproc$indu_7_TEXT == "Social Media and PR" , 1, I_vignette_df_preproc$indu)

# assign remaining ("Arts")
I_vignette_df_preproc$indu <- ifelse(I_vignette_df_preproc$indu == 7, 8, I_vignette_df_preproc$indu)

I_vignette_df_preproc$indu
tabyl(I_vignette_df_preproc$indu)

# Information, Communications, or Technology
# Finance, Real Estate, or Business Services
# Health, Education, Government, or Social and Consumer Services
# Wholesale, Retail
# Manufacturing, Logistics
# Agriculture, Extractive, or Construction
# Other, namely:
```


```{r}
## Reliabilities 
library("sjlabelled")
library(lubridate)
library(stringr)
library(zoo)
library(tidyverse)
library("tidyverse")

comp_dat <-  I_vignette_df_preproc %>% dplyr::select(dplyr::matches("cope|mani|chal|threat|quit|satis|PANA")) %>% remove_all_labels(.)

library(tidyr)
nrow(comp_dat)

matches <- dplyr::matches

comp_dat_single_item <- I_vignette_df_preproc %>% dplyr::select(dplyr::matches("finsit|exp_cond|t1timebuiss|coown|indu|age|gender|lang|edu|quitting1|locat|quitting "))  %>% remove_all_labels(.) %>% dplyr::select(-matches("UserLanguage|Q52_Page_Submit|Q53_Page_Submit|_TEXT|ifelse|age_1|LocationLatitude|LocationLongitude")) 

  
alph_dat <- comp_dat

comp_split <- comp_dat %>%
  split.default(sub("_.*", "", names(comp_dat))) 

alph_split <- alph_dat %>%
  split.default(sub("_.*", "", names(alph_dat))) 

comp <- purrr::map(comp_split, ~ rowMeans(.x), data = .x)
alph <- purrr::map(alph_split, ~ psych::alpha(.x), data = .x) %>%
  purrr::map(~ .x$total)

# add demos
comp_df_vig <- as.data.frame(do.call("cbind", comp)) %>% cbind(comp_dat_single_item)
alph_df_vig <- do.call("rbind", alph) %>% round(., 2)
```

## Reliabilities 

```{r include = TRUE}
alph_df_vig %>%
DT::datatable(
    extensions = 'Buttons', 
    options = list(dom = 'Bfrtip', 
                   buttons = c('excel', "csv"),
                   pageLength = 15))
```

## Correlations

```{r include = TRUE}
library(Hmisc)
comp_df = comp_df_vig %>% dplyr::select(-dplyr::matches("indu|locat|mani|edu")) %>% dplyr::select(exp_cond, quit, age, gender, finsit_1, finsit_2, coown, t1timebuiss)

correlation_matrix<-rcorr(as.matrix(comp_df), type="pearson")
#min(correlation_matrix$n) 
#max(correlation_matrix$n) 

comp_df$t1timebuiss <- comp_df$t1timebuiss/365

## Make table 
Mean <- round(colMeans(comp_df , na.rm =T),2)
SD <- round(apply(comp_df , 2, sd, na.rm =T),2)
mean_sd <- as.data.frame(rbind(Mean, SD)) %>% t()

corstar_select <- cbind(mean_sd, data.frame(corstars(comp_df, removeTriangle = "upper", result="none"))) 

rownames(corstar_select) <- c("1. Financial stress", "2. Quit intention", "3. Age", 
                              "4. Gender", "5. Business fin.sit", "6. Influence Covid-19", "7. Coownership", "8. Business age")

colnames(corstar_select) <- c("Mean", "SD", "1.", "2.", "3.", 
                              "4.", "5.", "6.", "7.")


corstar_select %>%
  DT::datatable(
    extensions = 'Buttons', 
    options = list(dom = 'Bfrtip', 
                   buttons = c('excel', "csv"),
                   pageLength = 15,
                  lengthMenu = c(25, 50, 75, 94)))

```
```{r}
library(xtable)
print(xtable(corstar_select, type = "latex"), file = "../output/cor_comp_vignette.tex")
```

## Manipulation checks

```{r include = TRUE}
exp = comp_df_vig[comp_df_vig$exp_cond == 2, ]
cond = comp_df_vig[comp_df_vig$exp_cond == 1, ]

t.test(exp$mani, cond$mani, alternative = "two.sided", var.equal = FALSE)

sd(exp$mani, na.rm = T)
sd(cond$mani)
```

## Hypothesis tests

### Fin. strain > Quit intention 

* with control variables

```{r include = TRUE}
library(lm.beta)
library(pander)
model2 <- lm(quit ~  exp_cond + age + gender + finsit_1 + finsit_2 + coown + t1timebuiss , data = comp_df_vig)
pander(summary(model2))

lm.beta(model2)
```
* without control variables

```{r include = TRUE}
library("lm.beta")
model2 <- lm(quit ~  exp_cond, data = comp_df_vig)
pander(summary(model2))
lm.beta(model2)

t.test(exp$quit, cond$quit, alternative = "two.sided", var.equal = FALSE)
cat("SD quit int experimental condition: ", sd(exp$quit,  na.rm = T))
cat("SD quit int control condition: ", sd(cond$quit,  na.rm = T))


```





