---
title: "Study_2_psycorona"
author: "Anne"
date: "12/20/2021"
output: html_document
---

# II PsyCorona


```{r include = TRUE}
# Rename
names(PsyCorona) <- gsub("PFS0", "fin_strain0", names(PsyCorona), fixed = TRUE)
df <- PsyCorona

library("dplyr")

df_e <- df %>% filter(!is.na(w4_employstatus_14))

df_e <-  df_e[!is.na(df_e$w5_SE_quit),] 

cat("Number of participants in the dataset:", nrow(df_e), "\n")

df_e$coded_country_text <- df_e$coded_country

## Get difference baseline w5

df_e$date_diff <- difftime(df_e$w5_StartDate, df_e$StartDate)

##Convert founding date

df_e$SE_start_recode <- as.numeric(names(attr(df_e$w5_SE_start,"labels")[match(df_e$w5_SE_start,attr(df_e$w5_SE_start,"labels"))]))
df_e$SE_start_recode <- 2020-df_e$SE_start_recode

# employees yes or no
df_e$w5_SE_employees_dich <- ifelse(df_e$w5_SE_employees_1 > 0, 1, 0)

```

```{r}
# raw data 
# 
df_e$coded_country_fac <- factor(df_e$coded_country)
df_e$coded_country_num <- as.numeric(df_e$coded_country_fac)

II_psycorona_df_raw <- df_e %>%
  dplyr::select( probSolving01, probSolving02, probSolving03, fin_strain01, fin_strain02, fin_strain03, w5_SE_quit, SE_start_recode, age, gender, edu, coded_country_num, w5_SE_employees_dich, coded_country) 

write.csv(II_psycorona_df_raw,"../raw_data/II_psycorona_df_raw.csv", row.names = FALSE)

```

## PREPROCESSING START 

```{r}
library(labelled)

var_label(II_psycorona_df_raw$coded_country) <- "Country of residence"
var_label(II_psycorona_df_raw$w5_SE_employees_dich) <- "Employees - yes or no?"
val_labels(II_psycorona_df_raw$w5_SE_employees_dich) <- c("Yes" = 1, "No" = 0)
var_label(II_psycorona_df_raw$SE_start_recode) <- "Years since business foundation"


CodeBook <-
as.data.frame(rbind(
  c("probSolving01",
    var_label(II_psycorona_df_raw$probSolving01),
    paste(get_labels(II_psycorona_df_raw$probSolving01, values = "p"), collapse = ", ")
  ),
 c("probSolving02",
    var_label(II_psycorona_df_raw$probSolving02),
    paste(get_labels(II_psycorona_df_raw$probSolving02, values = "p"), collapse = ", ")
  ),
 c("probSolving03",
    var_label(II_psycorona_df_raw$probSolving03),
    paste(get_labels(II_psycorona_df_raw$probSolving03, values = "p"), collapse = ", ")
  ),
 c("fin_strain01",
    var_label(II_psycorona_df_raw$fin_strain01),
    paste(get_labels(II_psycorona_df_raw$fin_strain01, values = "p"), collapse = ", ")
  ),
 c("fin_strain02",
    var_label(II_psycorona_df_raw$fin_strain02),
    paste(get_labels(II_psycorona_df_raw$fin_strain02, values = "p"), collapse = ", ")
  ),
 c("fin_strain03",
    var_label(II_psycorona_df_raw$fin_strain03),
    paste(get_labels(II_psycorona_df_raw$fin_strain03, values = "p"), collapse = ", ")
  ),
 c("w5_SE_quit",
    var_label(II_psycorona_df_raw$w5_SE_quit),
    paste(get_labels(II_psycorona_df_raw$w5_SE_quit, values = "p"), collapse = ", ")
  ),
 c("SE_start_recode",
    var_label(II_psycorona_df_raw$SE_start_recode),
    "ascending"
  ),
 c("age",
    var_label(II_psycorona_df_raw$age),
    paste(get_labels(II_psycorona_df_raw$age, values = "p"), collapse = ", ")
  ),
 c("gender",
    var_label(II_psycorona_df_raw$gender),
    paste(get_labels(II_psycorona_df_raw$gender, values = "p"), collapse = ", ")
  ),
 c("edu",
    var_label(II_psycorona_df_raw$edu),
    paste(get_labels(II_psycorona_df_raw$edu, values = "p"), collapse = ", ")
  ),
 c("w5_SE_employees_dich",
    var_label(II_psycorona_df_raw$w5_SE_employees_dich),
    paste(get_labels(II_psycorona_df_raw$w5_SE_employees_dich, values = "p"), collapse = ", ")
  ),
 c("coded_country",
    var_label(II_psycorona_df_raw$coded_country),
    paste(get_labels(II_psycorona_df_raw$coded_country, values = "p"), collapse = ", ")
 )
)
)

names(CodeBook) <- c("Variable name", "Description", "Values")

write.csv(CodeBook,"../Codebooks/II_psycorona_CodeBook.csv", row.names = FALSE)
```


```{r}
library(multicon)

# remove NA on relevant variables
# model <- lm(w5_SE_quit ~ fin_strain +  age + gender + SE_start_recode , data = comp_df)
II_psycorona_df_preproc <- II_psycorona_df_raw %>% drop_na(w5_SE_quit, age, gender, SE_start_recode)

comp_dat <- II_psycorona_df_preproc %>%
  dplyr::select(probSolving01, probSolving02, probSolving03, fin_strain01, fin_strain02, fin_strain03) 

comp_singleitem <- II_psycorona_df_preproc %>%
  dplyr::select(w5_SE_quit, SE_start_recode, age, gender, edu, coded_country_num, w5_SE_employees_dich) 

alph_dat <- comp_dat

comp_split <- comp_dat %>%
  split.default(sub("0.*", "", names(comp_dat))) 

alph_split <- alph_dat %>%
  split.default(sub("0.*", "", names(alph_dat))) 

comp <- purrr::map(comp_split, ~ multicon::composite(.x, nomiss = 0.8), data = .x)
alph <- purrr::map(alph_split, ~ psych::alpha(.x), data = .x) %>%
  purrr::map(~ .x$total)

# add demos
comp_df <- as.data.frame(do.call("cbind", comp))
alph_df <- do.call("rbind", alph) %>% round(., 2)


II_psycorona_df_preproc <- cbind(II_psycorona_df_preproc, comp_df)

comp_df <- cbind(comp_df, comp_singleitem) %>% remove_all_labels(.)
```

## PREPROCESSING END 


## Participant characteristics 

```{r}
set.seed(42)
  library(qwraps2)
# define the markup language we are working in.
# options(qwraps2_markup = "latex") is also supported.
options(qwraps2_markup = "markdown")
```


```{r include = T, echo = T}
tabyl(comp_df$gender)
# Age overview
II_psycorona_df_preproc$age_labeled <- names(attr(II_psycorona_df_preproc$age,"labels")[match(II_psycorona_df_preproc$age,attr(II_psycorona_df_preproc$age,"labels"))])

tabyl(II_psycorona_df_preproc$age_labeled)
tabyl(II_psycorona_df_preproc$age)

# Business age 
mean(II_psycorona_df_preproc$SE_start_recode)
sd(II_psycorona_df_preproc$SE_start_recode)

# Country 
library(dplyr)
tabyl(II_psycorona_df_preproc$coded_country) %>% arrange(desc(n))

# ge continent
library(countrycode)
II_psycorona_df_preproc <- as.data.frame(II_psycorona_df_preproc)
II_psycorona_df_preproc$region <- countrycode(sourcevar = II_psycorona_df_preproc[, "coded_country"],
                            origin = "country.name",
                            destination = "region23")

II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Australia and New Zealand"] = "Northern America, Australia & New Zealand"
II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Northern America"] = "Northern America, Australia & New Zealand"

II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "South America"] = "South & Central America"
II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Central America"] = "South & Central America"

II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Southern Africa"] = "Africa"
II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Northern Africa"] = "Africa"

II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Western Europe"] = "Europe"
II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Northern Europe"] = "Europe"
II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Eastern Europe"] = "Europe"
II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Southern Europe"] = "Europe"

II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Eastern Asia"] = "Eastern & South-Eastern Asia"
II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "South-Eastern Asia"] = "Eastern & South-Eastern Asia"

II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Western Asia"] = "Central and West Asia"
II_psycorona_df_preproc$region[II_psycorona_df_preproc$region == "Central Asia"] = "Central and West Asia"

tabyl(II_psycorona_df_preproc$region) %>% arrange(desc(n))
```

## Reliabilities

```{r include = TRUE}
## Correlations and reliabilities 

alph_df %>%
DT::datatable(
    extensions = 'Buttons', 
    options = list(dom = 'Bfrtip', 
                   buttons = c('excel', "csv"),
                   pageLength = 15))
```

## Correlations

```{r include = TRUE}
#comp_df$date_diff <- as.numeric(comp_df$date_diff)

# remove age, and irrelevant columns  
comp_df_sel <- comp_df %>% dplyr::select(-dplyr::matches("probSolving|w5_lifeSat|coded_country_num|w5_fin_strain01|w7_SE_quit|w5_SE_employees_dich"))  %>% .[, c(1, 2, 4, 5, 3)]

cor <- round(cor(comp_df_sel, use="pairwise.complete.obs"), 2)

Mean <- round(colMeans(comp_df_sel, na.rm =T),2)
SD <- round(apply(comp_df_sel, 2, sd, na.rm =T),2)

mean_sd <- as.data.frame(rbind(Mean, SD)) %>% t()

library(dplyr)
library(Hmisc)
correlation_matrix<-rcorr(as.matrix(comp_df_sel), type="pearson")

## Make table 
Mean <- round(colMeans(comp_df_sel , na.rm =T),2)
SD <- round(apply(comp_df_sel , 2, sd, na.rm =T),2)
mean_sd <- as.data.frame(rbind(Mean, SD)) %>% t()

corstar_select <- cbind(mean_sd, data.frame(corstars(comp_df_sel, removeTriangle = "upper", result="none"))) 

rownames(corstar_select) <- c("1. Fin. stress", "2. Quit intention", "3. Age", 
                              "4. Gender", "5. Business age")

colnames(corstar_select) <- c("Mean", "SD", "1.", "2.", "3.", 
                              "4.")


corstar_select %>%
  DT::datatable(
    extensions = 'Buttons', 
    options = list(dom = 'Bfrtip', 
                   buttons = c('excel', "csv"),
                   pageLength = 15,
                  lengthMenu = c(25, 50, 75, 94)))

```

```{r}
## preprocessed dataset 
write.csv(II_psycorona_df_preproc,"../preprocessed_data/II_psycorona_df_preproc.csv", row.names = FALSE)
```


```{r}
library(xtable)
print(xtable(corstar_select, type = "latex"), file = "../output/cor_comp_psycorona.tex")
```


## Hypotheses tests

### Lagged

#### T1 fin. stress > T2 quit 


```{r include = TRUE}
library(lavaan)
model <- '
T2quitint =~ w5_SE_quit 
w5_SE_quit~~0*w5_SE_quit
T1finstrain =~ fin_strain01 + fin_strain02 + fin_strain03 
T2quitint ~ T1finstrain + age + gender + SE_start_recode
         '
medmodel_result <- sem(model, data = II_psycorona_df_preproc)

summary(medmodel_result, fit.measures=TRUE, standardized = TRUE)
```

```{r}
library("semTable")
semTable( medmodel_result, file = NULL, paramSets = c("slopes","constructed","fits"),
         paramSetLabels = c("slopes" = "Direct effects", "constructed" = "Indirect and total effects","fits" = "Fit Indices"), 
         columns = c(est = "Est", se = "SE", p = "\textit{p}"),
         varLabels = c("T1finstrain" = "T1 Fin. stress", "T1affcom" = "T1 Affective com.", "T2quitint" = "T2 Quit intention","T1concom" = "T1 Continuance com.",  "a1b1" = "Indirect effect", "a2b2" = "Indirect effect",
                       "total" = "Total effect", "age" = "Age", "gender" = "Gender", "SE_start_recode" = "Business age"), groups = NULL,
         type = "latex", table.float = FALSE, caption = NULL,  fits = c("chisq","rmsea","cfi","tli","srmr"),
         label = NULL, longtable = TRUE,
         centering = "siunitx", alpha = c(0.05, 0.01, 0.001))
```



