---
title: "Entrepreneurs' financial strain"
author: "Anne"
date: '`r Sys.Date()`'
bibliography: ../refs/refs.bib
csl: ../refs/apa7.csl
mainfont: Times New Roman
output:
  html_document:
    toc: true
    theme: united 
    toc_depth: 5
    toc_float: true
---

# Overview


```{r loading_packs, include = F, echo = F}

source("../R/remote_functions.R")
# Packages 
knitr::opts_chunk$set(include = F, echo=FALSE, warning=FALSE, message=FALSE)


packages <- c("mediation", "foreign", "tidyverse","stargazer","multicon", "ggplot2", "plyr", "reshape2", "readxl", 
              "scales", "grid", "tidyLPA", "Rcpp", "naniar", "dplyr", "car", "mice", 
              "rstudioapi", "labelled", "modi", "semPlot", "kulife", "knitr", "janitor", "DT", "sjlabelled", "kableExtra",
              "semoutput", "pander", "qwraps2", "semTable")



ipak(packages)
```


```{r loading_data, include = FALSE}
# Load data 

options(knitr.table.format = function() {
  if (knitr::is_latex_output()) 'latex' else 'pandoc'
})

library(rlang)
library(tidyverse)
library(foreign)
setwd("./../..")
files <- dir(paste0(getwd(),"/data/"), pattern = "\\.sav$", full.names = FALSE) 

df_list <- vector("list", length(files))
names(df_list) <- files

df_list <- read_in(files, directory = "data/")

list2env(df_list,envir=.GlobalEnv)


library(magrittr)

```

```{r, include=FALSE}
I_students_india <- FALSE
II_psycorona <- TRUE
III_observational <- TRUE
IV_vignette <- TRUE
```

```{r, child=if (I_students_india) 'I_students_india.Rmd'}
```

```{r, child=if (IV_vignette) 'IV_vignette.Rmd'}
```

```{r, child=if (II_psycorona) 'II_psycorona.Rmd'}
```

```{r, child=if (III_observational) 'III_observational.Rmd'}
```

# References

<div id="refs"></div>






